ipy:
  image: 'tutum.co/burnstony/scipyserver:latest'
  ports:
    - '8080:8080'
  volumes_from:
    - data_data_1
converted:
  image: 'tutum.co/burnstony/icontent_convert:latest'
  volumes_from:
    - data_data_1
nginxone:
  image: 'tutum.co/burnstony/nginxone:latest'
  ports:
    - '80:80'
  volumes_from:
    - data_data_1
