data:
  image 'burnstony/icontent.data:latest'
ipy:
  image: 'burnstony/scipyserver:latest'
  ports:
    - '8080:8080'
  volumes_from:
    - data
converted:
  image: 'burnstony/icontent_convert:latest'
  volumes_from:
    - data
nginxone:
  image: 'burnstony/nginxone:latest'
  ports:
    - '80:80'
  volumes_from:
    - data
